/// @Project by Kucia Guillaume* ///


// CREATE VARIABLES
TYPE = "NULL";
OPTION = "NULL";
TAG = "NULL";
image_alpha = 0;

// INIT OPTION VARIABLES
FADE_IN = false;
FADE_SATE = false;
FADE_POWER = 0;
FIRST_PASS = false;

//FADE ON
FADE_ON = false;
FADE_ON_POWER = 0;

// INFO
INFO = false;
INFO_NAME = "NULL";

// ACTION
CLOSE = false;

// window
WINDOW = "NULL";
ON_TASK = "NULL";
Y_TARGET = 0;
Y_BASE = 0;
OPT_CLOSING = false;
WINDOWS_BUTTONS = ["NULL"];
PIN = false;

CREATE_WINDOW_IMAGE = "NULL";
CREATE_WINDOW_TAG = "NULL";
CREATE_WINDOW_ICON = "NULL";
CREATE_WINDOW_NAME = "NULL";
VISIO_TIME = 0;

