/// @Project by Kucia Guillaume* ///


// CREATE VARIABLES
TYPE = "NULL";
OPTION = "NULL";
TAG = "NULL";
image_alpha = 0;
CLOSE = false;

// INIT OPTION VARIABLES
FADE_IN = false;
FADE_SATE = false;
FADE_POWER = 0;
FIRST_PASS = false;

//FADE ON
FADE_ON = false;
FADE_ON_POWER = 0;

// INFO
INFO = false;
INFO_NAME = "NULL";

// window
WINDOW = "NULL";
Y_TARGET = 0;
OPT_CLOSING = false;
OBJECT_LINKED = "NULL";
CREATE = false;

// VARIABLES FOR FILE EXPLORER
SEARCH = "NULL";
PWD = ON_MAIN_SCENE.PATH;
PWD_PATH = "/~";
PATH = "NULL";
FOLDER_LIST = ["NULL"];
EXPLORER_RELOAD = "NULL";
EXPLORER_SLIDER = "NULL";
N_ELEMENTS = 0;
ELEMENTS = "NULL";
GO_ROOT = "NULL";
GO_BACK = "NULL";
EMPTY_FOLDER = "NULL";