/// @Project by Kucia Guillaume* ///

// CREATE VARIABLEs
TYPE = "NULL";
TAG = "NULL";
OPTION = ["NULL"];
TITLE_CONNECT = "NULL";
DESCRIPTION_CONNECT = "NULL";
ICON_CONNECT = "NULL";
NOTIF_TIME = 0;
CLOSE_CONNECT = "NULL;"

// INIT ALL OPTION;
LOCK = ["NULL", "NULL"];
WALLPAPER_INDEX = -1;
WALLPAPER = false;

//POSITIONS
OPT_POSITIONS = false;
OPT_X = 0;
OPT_Y = 0;

// FADE ON
FADE_ON = false;
FADE_ON_POWER = 0;

// INIT OPTION VARIABLES
FADE_IN = false;
FADE_SATE = false;
FADE_POWER = 0;
FIRST_PASS = false;
image_alpha = 0;

// INFO
INFO = false;
INFO_NAME = "NULL";
