/// @Project by Kucia Guillaume* ///

// CREATE VARIABLEs
TYPE = "NULL";
TAG = "NULL";
OPTION = ["NULL"];

// INIT ALL OPTION;
LOCK = ["NULL", "NULL"];
LOCK_STATE = false;
OBJECT_LINKED = "NULL";
TEXT_CONNECT = "NULL";
DESTROY = DestroyButtonBox;

// SLEF
SELF = "NULL";

// INIT OPTION VARIABLES
FADE_IN = false;
FADE_SATE = false;
FADE_POWER = 0;
FIRST_PASS = false;
image_alpha = 0;

//FADE ON
FADE_ON = false;
FADE_ON_POWER = 0;

// INFO
INFO = false;
INFO_NAME = "NULL";

// WINDOW
PARENT = "NULL";
OTHER_PARENT = "NULL";
VISIO_TAG = "NULL";
ON = true;

// EXPLORER
GET_EXPLORER = "NULL";
PARENT_DIFF_X = 0;
PARENT_DIFF_Y = 0;
PARENT = "NULL";
DOCK_TYPE_TEXT = "NULL";

// EXPLORER REFRESH
REFRESH = false;
REFRESH_TIME = 0;
REFRESH_LOAD = "NULL";
GET_FOLDER = "NULL";
EXPLORER_SELECT = false;

/// FOLDER
ORIGINAL_NAME = "NULL";
MASTER_NAME = "NULL";
RENAME_OBJECT = "NULL";
GET_FOLDER = "NULL";
NAME = "NULL";

